### ISSUE TITLE
Alt-Left & Alt-Right Support?

### ISSUE THREAD

**Issue by steviegt6** [TheLuxure/AltLibrary#10]
So I came across this library the other day and I noticed that it doesn't allow me to radicalize myself. This is a missing feature I believe?

**Comment by steviegt6** [comment]
@BasicallyIAmFox, please get back to me soon! Thank you!

**Comment by BasicallyIAmFox** [comment]
what do you want from me again @steviegt6

**Comment by BasicallyIAmFox** [comment]
@steviegt6 what do you want guh
